In [5]:
import numpy as np
from scipy.ndimage import binary_dilation, binary_erosion

# เมทริกซ์ต้นฉบับ
input_image_dilation = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 0, 1, 1, 0],
    [0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0]
])
# โครงสร้างแม่แบบ
structuring_element_dilation = np.array([
    [0, 1, 0],
    [1, 1, 1],
    [0, 1, 0]
])
# ทำ Dilation
output_image_dilation = binary_dilation(input_image_dilation, structure=structuring_element_dilation).astype(int)
print("ผลลัพธ์หลังการทำ Dilation:")
print(output_image_dilation)

input_image_erosion = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0]
])
structuring_element_erosion = np.array([
    [0, 0, 0],
    [1, 1, 0],
    [0, 1, 0]
])
# ทำ Erosion
output_image_erosion = binary_erosion(input_image_erosion, structure=structuring_element_erosion).astype(int)

print("\nผลลัพธ์หลังการทำ Erosion:")
print(output_image_erosion)

ผลลัพธ์หลังการทำ Dilation:
[[0 1 1 0 0]
 [1 1 1 1 0]
 [0 1 1 1 1]
 [1 1 1 1 0]
 [0 1 1 0 0]]

ผลลัพธ์หลังการทำ Erosion:
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
